services:
  website:
    image: ajferrario/distill-website
    container_name: website
    networks:
      - distill_network
    restart: always

  cloudflare_ddns:
    image: ajferrario/cloudflare-ddns
    container_name: cloudflare_ddns
    restart: always
    networks:
      - distill_network
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - RECORD_NAMES=${RECORD_NAMES}

  caddy_proxy:
    image: ajferrario/caddy-proxy
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always
    networks:
      - distill_network
    volumes:
      - caddy_data:/data
      - ${CF_CERT_PATH}:/certs/certificate.pem
      - ${CF_PRIVATE_KEY_PATH}:/certs/key.pem

networks:
  distill_network:
    external: true

volumes:
  caddy_data:
  caddy_certs:
