version: '3.8'

services:
  data_loader:
    build:
      context: ./services/data_loader
    image: ajferrario/distill-data-loader:latest

  discord_bot:
    build:
      context: ./services/discord_bot
    image: ajferrario/distill-discord-bot:latest
  
  query_server:
    build:
      context: ./services/query_server
    image: ajferrario/distill-query-server