services:
  data_loader:
    image: ajferrario/distill-data-loader:latest
    env_file:
      - ${ENV_FILE}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - SERVICE_ACCOUNT_KEY=${SERVICE_ACCOUNT_KEY}
    runtime: nvidia
    container_name: data_loader
    networks:
      - distill_network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  query_server:
    image: ajferrario/distill-query-server:latest
    env_file:
      - ${ENV_FILE}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    container_name: llama-index.${CUSTOMER_ID}
    ports:
      - "8001:8001"
    networks:
      - distill_network
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  distill_network:
    external: true