services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm.${CUSTOMER_ID}
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="make this a large list of random numbers and letters 20+"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://ollama:11434
      - OLLAMA_MODEL_PREF=llama3:latest
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://ollama:11434
      - EMBEDDING_MODEL_PREF=mxbai-embed-large:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      - AGENT_SERPER_DEV_KEY="SERPER DEV API KEY"
      - AGENT_SERPLY_API_KEY="Serply.io API KEY"
    volumes:
      - anythingllm_storage:/app/server/storage
    networks:
      - distill_network
    restart: always

  configure_customer:
    image: ajferrario/distill-configure-customer
    container_name: configure_customer
    environment:
      - API_KEY=${API_KEY}
      - CUSTOMER_ID=${CUSTOMER_ID}
      - MANAGER_ACCOUNT_USERNAME=${MANAGER_ACCOUNT_USERNAME}
      - ADMIN_ACCOUNT_PASSWORD=${ADMIN_ACCOUNT_PASSWORD}
      - DISCORD_SERVER_IDS=${DISCORD_SERVER_IDS}
      - SLACK_WORKSPACE_IDS=${SLACK_WORKSPACE_IDS}
    networks:
      - distill_network

volumes:
  anythingllm_storage:

networks:
  distill_network:
    external: true