version: '3.8'

services:
  chromadb:
    image: chromadb/chroma
    environment:
      - IS_PERSISTENT=TRUE
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_volume:/chroma/chroma
    networks:
      - distill_network
    restart: always

  ollama:
    image: ajferrario/distill-preloaded-ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
    networks:
      - distill_network
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  discord_bot:
    image: ajferrario/distill-discord-bot
    environment:
      REST_SERVER_PORT: 8001
    container_name: discord_bot
    networks:
      - distill_network

networks:
  distill_network:
    name: distill_network
    driver: bridge

volumes:
  chroma_volume:
  ollama_volume:
