services:
  caddy_proxy:
    build:
      context: ./services/caddy_proxy
    image: ajferrario/caddy-proxy:latest

  cloudflare_ddns:
    build:
      context: ./services/cloudflare_ddns
    image: ajferrario/cloudflare-ddns:latest

  discord_bot:
    build:
      context: ./services/discord_bot
    image: ajferrario/distill-discord-bot:latest
  
  slack_app:
    build:
      context: ./services/slack_app
    image: ajferrario/distill-slack-app:latest

  website:
    build:
      context: ./services/website
    image: ajferrario/distill-website:latest