version: '3.8'

services:
  discord_bot:
    build:
      context: ./services/discord_bot
    image: ajferrario/distill-discord-bot:latest
  
  slack_app:
    build:
      context: ./services/slack_app
    image: ajferrario/distill-slack-app:latest