services:
  website:
    image: ajferrario/distill-website
    container_name: website
    networks:
      - distill_network
    restart: always

  namecheap_dns_updater:
    image: ajferrario/namecheap-dns-updater:latest
    container_name: namecheap_dns_updater
    restart: always
    networks:
      - distill_network
    environment:
      - DDNS_API_KEY=${DDNS_API_KEY}
      - DOMAIN_NAME=${DOMAIN_NAME}

  reverse_proxy:
    image: ajferrario/reverse-proxy:latest
    container_name: reverse_proxy
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    networks:
      - distill_network
    restart: always
    depends_on:
      - website

  certbot:
    image: ajferrario/certbot:latest
    container_name: certbot
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    volumes:
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    networks:
      - distill_network
    depends_on:
      - namecheap_dns_updater
    restart: always

networks:
  distill_network:
    external: true

volumes:
  certs:
  challenge:
  nginx:
