services:
  customer_db:
    image: redis/redis-stack:latest
    container_name: customer_db
    ports:
      - "8001:8001"
    volumes:
      - redis-data:/data
    networks:
      - distill_network

volumes:
  redis-data:

networks:
  distill_network:
    external: true