services:
  discord_bot:
    build: .
    environment:
      DISCORD_BOT_KEY: ${DISCORD_BOT_KEY}
    container_name: discord_bot
    networks:
      - distill_network
    restart: always


networks:
  distill_network:
    external: true