services:
  configure_customer:
    build: .
    container_name: configure_customer
    environment:
      - API_KEY=${API_KEY}
      - CUSTOMER_ID=${CUSTOMER_ID}
      - MANAGER_ACCOUNT_USERNAME=${MANAGER_ACCOUNT_USERNAME}
      - ADMIN_ACCOUNT_PASSWORD=${ADMIN_ACCOUNT_PASSWORD}
      - DISCORD_SERVER_IDS=${DISCORD_SERVER_IDS}
      - SLACK_WORKSPACE_IDS=${SLACK_WORKSPACE_IDS}
    networks:
      - distill_network

networks:
  distill_network:
    external: true